name = "remote-tldraw-sync"
main = "worker/worker.ts"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
account_id = "d18d2804fcada0285bb3f0e5ff7a2f08"

[assets]
not_found_handling = "single-page-application"
directory = "./example/client"

[observability]
enabled = true

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" },
]

[[routes]]
pattern = "remote-tldraw-sync.jiachen023212.workers.dev"
custom_domain = true

# Durable objects require migrations to create/modify/delete them
[[migrations]]
tag = "v1"
new_sqlite_classes  = ["TldrawDurableObject"]

# We store rooms and asset uploads in an R2 bucket
[[r2_buckets]]
binding = 'TLDRAW_BUCKET'
bucket_name = 'remote-tldraw-collaboration'
preview_bucket_name = 'multiplayer-template-preview'
